[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
# عنوان الموقع الرئيسي
site_url = "https://ahmadi-store.vercel.app"
# عناوين Redirect المسموح بها
additional_redirect_urls = [
  "https://ahmadi-store.vercel.app/**",
  "https://ahmadi-store.vercel.app/auth/callback",
  "http://localhost:3000/**",
  "http://localhost:3000/auth/callback",
]
jwt_expiry = 3600
enable_signup = true
email_confirm_changes = true
email_otp_exp = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.sms]
enable_signup = false
enable_confirmations = false
