import { NextRequest, NextResponse } from "next/server";
import { requireAdmin } from "@/lib/admin-auth";
import { createClient } from "@supabase/supabase-js";
import { listStaffAccounts, setStaffTabs, generateStaffPassword } from "@/lib/admin/staff";

function svc() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { persistSession: false } },
  );
}

// GET — قائمة حسابات الموظفين وما يملكه كل منهم من تبويبات
export async function GET() {
  const { error } = await requireAdmin("users:manage");
  if (error) return error;

  const staff = await listStaffAccounts(svc());
  return NextResponse.json({ staff });
}

// POST — إنشاء حساب موظف جديد ومنحه تبويبات محددة
// Body: { email, full_name, password?, tabs: string[] }
export async function POST(request: NextRequest) {
  const { error } = await requireAdmin("users:manage");
  if (error) return error;

  const body = await request.json().catch(() => ({})) as {
    email?: string; full_name?: string; password?: string; tabs?: string[];
  };
  const email    = body.email?.trim().toLowerCase();
  const fullName = body.full_name?.trim();
  if (!email || !fullName) {
    return NextResponse.json({ error: "الاسم والبريد الإلكتروني مطلوبان" }, { status: 400 });
  }

  const autoGenerated = !body.password?.trim();
  const password = body.password?.trim() || generateStaffPassword();
  if (password.length < 8) {
    return NextResponse.json({ error: "كلمة المرور 8 أحرف على الأقل" }, { status: 400 });
  }

  const client = svc();
  const { data: created, error: createErr } = await client.auth.admin.createUser({
    email, password, email_confirm: true,
    user_metadata: { full_name: fullName },
  });
  if (createErr || !created.user) {
    return NextResponse.json({ error: createErr?.message ?? "فشل إنشاء الحساب" }, { status: 400 });
  }

  const userId = created.user.id;
  // trigger handle_new_user يُنشئ صف profiles تلقائياً — نضبط الاسم الكامل الصحيح
  await client.from("profiles").update({ full_name: fullName }).eq("id", userId);
  await setStaffTabs(client, userId, body.tabs ?? []);

  return NextResponse.json({
    success: true, user_id: userId,
    password: autoGenerated ? password : undefined,
  }, { status: 201 });
}
